## Basic Function Numpy modul

In [1]:
import numpy as np
array1=np.array([[3,4,5,6,8],[1,3,7,8,6]], dtype='int32')
print(array1)

[[3 4 5 6 8]
 [1 3 7 8 6]]


In [2]:
array1.shape

(2, 5)

In [3]:
array1.dtype

dtype('int32')

In [4]:
np.zeros((4,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [5]:
np.ones(7).dtype

dtype('float64')

In [6]:
np.empty((4,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [7]:
arr=np.arange(1000000)

In [8]:
%time for _ in range(10):arr=arr*3

CPU times: total: 62.5 ms
Wall time: 62.4 ms


In [9]:
np.array([2,3,4,5,6,7,8,9])

array([2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
array1

array([[3, 4, 5, 6, 8],
       [1, 3, 7, 8, 6]])

In [11]:
array1**array1

array([[      27,      256,     3125,    46656, 16777216],
       [       1,       27,   823543, 16777216,    46656]])

In [12]:
np.array([12**12])

array([8916100448256], dtype=int64)

In [13]:
1/array1

array([[0.33333333, 0.25      , 0.2       , 0.16666667, 0.125     ],
       [1.        , 0.33333333, 0.14285714, 0.125     , 0.16666667]])

## Slicing

In [14]:
array2=np.array([4,5,32,6,7,8])

In [15]:
arr=array2[4:6].copy()

In [16]:
arr

array([7, 8])

In [17]:
arr[0]=9

In [18]:
array2

array([ 4,  5, 32,  6,  7,  8])

In [19]:
array1

array([[3, 4, 5, 6, 8],
       [1, 3, 7, 8, 6]])

In [22]:
array1[0,3]

6